name: npy
description: Handle numpy binary (NPY and NPZ) files in Dart.
version: 0.1.0
repository: https://github.com/minhqdao/npy

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^3.6.1

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.8
